/** Pure rules for the per-location menu, hidden locations and pinned locations.
 *
 *  Everything here is keyed by the location's ENDPOINT key (`serverKey`), never
 *  by `ServerEntry.id`: a refresh regenerates every entry id, so an id-keyed
 *  "hidden" list would forget what the user hid, and a provider that rotates the
 *  endpoint inside a profile would resurrect it. Keys therefore behave exactly
 *  like the selection identity does (see `subscription-selection.ts`).
 *
 *  A location that belongs to a manually added configuration is DELETED, because
 *  nothing regenerates it. A location that came from a subscription can only be
 *  HIDDEN, because the next fetch would bring it back — hiding is the honest
 *  verb there, and how long it lasts is a user setting.
 */

/** Order of the pinned locations among themselves. Unpinned locations always
 *  keep the provider's own order. */
export type PinOrder = "newestLast" | "newestFirst";

export type LocationAction =
  | "ping"
  | "rename"
  | "pin"
  | "unpin"
  | "hide"
  | "unhide"
  | "delete";

export interface LocationMenuState {
  /** False for a manually added configuration card. */
  fromSubscription: boolean;
  hidden: boolean;
  pinned: boolean;
}

/** Menu items for one location, top to bottom. */
export function locationActions(state: LocationMenuState): LocationAction[] {
  const items: LocationAction[] = ["ping", "rename"];
  items.push(state.pinned ? "unpin" : "pin");
  if (state.fromSubscription) {
    items.push(state.hidden ? "unhide" : "hide");
  } else {
    // A manual location is not regenerated by anything, so it can go for real.
    items.push("delete");
  }
  return items;
}

/** True when the location must be kept out of the list right now.
 *
 *  Hiding has no duration setting on purpose. A hidden row stays hidden until the
 *  user shows it again on the card, and the only other way back is removing the
 *  subscription and importing it again -- a re-import is a new subscription, not a
 *  refresh of the old one. Nothing brings a location back by itself: a background
 *  update is not something the user did, and a refresh he did do is not an undo. */
export function isHiddenLocation(
  key: string,
  hiddenKeys: readonly string[],
  revealHidden: boolean,
): boolean {
  if (revealHidden) return false;
  return hiddenKeys.includes(key);
}

export interface OrderedLocations<T> {
  /** Locations to render, in display order. */
  visible: T[];
  /** Locations the user hid, in provider order (rendered dimmed while the card
   *  reveals them, counted otherwise). */
  hidden: T[];
}

/** Split and order the list: hidden locations drop out, pinned locations move to
 *  the TOP of the list (ordered by pin time, direction configurable), everything
 *  else keeps the provider's order. */
export function orderLocations<T>(
  servers: readonly T[],
  opts: {
    keyOf: (server: T) => string;
    hiddenKeys: readonly string[];
    pinnedAt: Readonly<Record<string, number>>;
    revealHidden: boolean;
    pinOrder: PinOrder;
  },
): OrderedLocations<T> {
  const shown: T[] = [];
  const hidden: T[] = [];
  for (const server of servers) {
    if (isHiddenLocation(opts.keyOf(server), opts.hiddenKeys, opts.revealHidden)) {
      hidden.push(server);
    } else {
      shown.push(server);
    }
  }

  const timeOf = (server: T): number | undefined =>
    opts.pinnedAt[opts.keyOf(server)];
  const pinned = shown.filter((s) => timeOf(s) !== undefined);
  const rest = shown.filter((s) => timeOf(s) === undefined);
  pinned.sort((a, b) => {
    const ta = timeOf(a) ?? 0;
    const tb = timeOf(b) ?? 0;
    if (ta === tb) return 0;
    return opts.pinOrder === "newestFirst" ? tb - ta : ta - tb;
  });

  // Pinned first, like the pinned card above them.
  return { visible: [...pinned, ...rest], hidden };
}

/** How many hidden locations to advertise on the card. */
export function hiddenCount<T>(
  servers: readonly T[],
  keyOf: (server: T) => string,
  hiddenKeys: readonly string[],
): number {
  let n = 0;
  for (const server of servers) {
    if (hiddenKeys.includes(keyOf(server))) n += 1;
  }
  return n;
}
